export_file(
    name = "merge_jars.py",
    src = "merge_jars.py",
    visibility = ["PUBLIC"],
)

export_file(
    name = "fabric_dev_launcher.sh",
    src = "fabric_dev_launcher.sh",
    visibility = ["PUBLIC"],
)
